enable_transport = true
share_instance = true
shared_instance_port = 37430
instance_control_port = 37431
panic_on_interface_error = false
loglevel = 4

[interfaces]
  [interfaces."RNS Testnet Amsterdam"]
  type = "TCPClientInterface"
  enabled = true
  target_host = "amsterdam.connect.reticulum.network"
  target_port = 4965

  [interfaces."RNS Testnet BetweenTheBorders"]
  type = "TCPClientInterface"
  enabled = true
  target_host = "reticulum.betweentheborders.com"
  target_port = 4242

  [[Local UDP]]
    type = "UDPInterface"
    interface_enabled = true
    address = "0.0.0.0"
    port = 37698

  [[Auto Discovery]]
    type = "AutoInterface"
    interface_enabled = true
    discovery_port = 29718
    data_port = 42673 