enable_transport = true
share_instance = true
shared_instance_port = 37428
instance_control_port = 37429
panic_on_interface_error = false
loglevel = 4

[interfaces]
  [interfaces."Local TCP"]
  type = "TCPClientInterface"
  enabled = true
  target_host = "rns.quad4.io"
  target_port = 4242

  [interfaces."Local UDP"]
  type = "UDPInterface"
  enabled = true
  interface = "lo"
  address = "127.0.0.1"
  port = 37428
  target_address = "127.0.0.1"
  target_port = 37430