name: Run Gosec
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
