name: Performance Monitor

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  performance-monitor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: '1.25'

    - name: Build
      run: |
        go build -o bin/reticulum-go ./cmd/reticulum-go

    - name: Run Performance Monitor
      id: monitor
      run: |
        cp tests/scripts/monitor_performance.sh .
        chmod +x monitor_performance.sh
        ./monitor_performance.sh